# For more info, please check out: https://github.com/marketplace/actions/android-emulator-runner

name: AndroidEmulator

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Sdl Android Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 29
        script: ./android/gradlew -p ./android :sdl_android:connectedCheck

    - name: Hello Sdl Android Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 29
        script: ./android/gradlew -p ./android :hello_sdl_android:test
